# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'incomesourcerecommendation.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_incomereco(object):
    def setupUi(self, incomereco):
        incomereco.setObjectName("incomereco")
        incomereco.resize(550, 500)
        incomereco.setMinimumSize(QtCore.QSize(550, 500))
        incomereco.setMaximumSize(QtCore.QSize(550, 500))
        self.centralwidget = QtWidgets.QWidget(incomereco)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.fatherNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.fatherNameLabel.setObjectName("fatherNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fatherNameLabel)
        self.fatherNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fatherNameLineEdit.setObjectName("fatherNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fatherNameLineEdit)
        self.AddressLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddressLabel.setObjectName("AddressLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.AddressLabel)
        self.wardNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.wardNoLabel.setObjectName("wardNoLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel)
        self.wardNoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.wardNoLineEdit.setObjectName("wardNoLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wardNoLineEdit)
        self.municipalityLabel = QtWidgets.QLabel(self.centralwidget)
        self.municipalityLabel.setObjectName("municipalityLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.municipalityLabel)
        self.municipalityLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.municipalityLineEdit.setObjectName("municipalityLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.municipalityLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        incomereco.setCentralWidget(self.centralwidget)

        self.retranslateUi(incomereco)
        QtCore.QMetaObject.connectSlotsByName(incomereco)

    def retranslateUi(self, incomereco):
        _translate = QtCore.QCoreApplication.translate
        incomereco.setWindowTitle(_translate("incomereco", "Income Source Recommendation"))
        self.nameLabel.setText(_translate("incomereco", "Name"))
        self.fatherNameLabel.setText(_translate("incomereco", "Father\'s Name"))
        self.AddressLabel.setText(_translate("incomereco", "<b>Address"))
        self.wardNoLabel.setText(_translate("incomereco", "Ward No."))
        self.municipalityLabel.setText(_translate("incomereco", "Municipality"))
        self.pushButton.setText(_translate("incomereco", "Add"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("incomereco", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("incomereco", "S.N."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("incomereco", "Details"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("incomereco", "Amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("incomereco", "Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("incomereco", "Remarks"))
