# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signup(object):
    ##test for signup button<pshreyam>##################################################
    def signupcheck(self):
        print("signup button pressed")
    #############################################################################
    ##test for login refer button <pshreyam>#######################################
    def refer2fxn(self):
        print("Button pressed.We enter the login page.")
        self.stackedWidget.setCurrentIndex(1)
    ###############################################################################
    ##test for signup refer button <pshreyam>#######################################
    def referfxn(self):
        print("Button pressed.We enter the signup page.")
        self.stackedWidget.setCurrentIndex(0)
    ##################################################################################    
    def setupUi(self, Signup):
        Signup.setObjectName("Signup")
        Signup.resize(800, 600)
        Signup.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(118, 32, 153, 245), stop:1 rgba(255, 255, 255, 255));")
        self.Signup_2 = QtWidgets.QWidget(Signup)
        self.Signup_2.setObjectName("Signup_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Signup_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 30, 771, 521))
        self.stackedWidget.setStyleSheet("background::rgb(34, 130, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Sign_up = QtWidgets.QWidget()
        self.Sign_up.setObjectName("Sign_up")
        self.groupBox = QtWidgets.QGroupBox(self.Sign_up)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 721, 481))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background:black;\n""border-radius:20px; \n""color:red;")
        self.groupBox.setObjectName("groupBox")
        self.fullname = QtWidgets.QLabel(self.groupBox)
        self.fullname.setGeometry(QtCore.QRect(40, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.fullname.setFont(font)
        self.fullname.setStyleSheet("color:white;")
        self.fullname.setObjectName("fullname")
        self.fname = QtWidgets.QLineEdit(self.groupBox)
        self.fname.setGeometry(QtCore.QRect(190, 90, 151, 31))
        self.fname.setStyleSheet("background:white;\n""color:black;")
        self.fname.setObjectName("fname")
        self.signup = QtWidgets.QPushButton(self.groupBox)
        self.signup.setGeometry(QtCore.QRect(320, 390, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.signup.setFont(font)
        self.signup.setStyleSheet("background:red;\n""color:black;\n""border-radius:20px;")
        self.signup.setObjectName("signup")
        ##testing signup button#####################################<pshreyam>
        self.signup.clicked.connect(self.signupcheck)
        ############################################################
        self.exit_2 = QtWidgets.QPushButton(self.groupBox)
        self.exit_2.setGeometry(QtCore.QRect(480, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.exit_2.setFont(font)
        self.exit_2.setStyleSheet("background:red;\n""color:black;\n""border-radius:20px;")
        self.exit_2.setObjectName("exit_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(50, 330, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:white;")
        self.checkBox.setObjectName("checkBox")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(190, 140, 151, 31))
        self.username.setStyleSheet("background:white;\n""color:black;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(190, 190, 151, 31))
        self.password.setStyleSheet("background:white;\n""color:black;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.repassword = QtWidgets.QLineEdit(self.groupBox)
        self.repassword.setGeometry(QtCore.QRect(520, 190, 151, 31))
        self.repassword.setStyleSheet("background:white;\n""color:black;")
        self.repassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword.setObjectName("repassword")
        self.repass = QtWidgets.QLabel(self.groupBox)
        self.repass.setGeometry(QtCore.QRect(380, 200, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.repass.setFont(font)
        self.repass.setStyleSheet("color:white;")
        self.repass.setObjectName("repass")
        self.date = QtWidgets.QLineEdit(self.groupBox)
        self.date.setGeometry(QtCore.QRect(380, 240, 81, 31))
        self.date.setStyleSheet("background:white;\n""color:black;")
        self.date.setObjectName("date")
        self.month = QtWidgets.QLineEdit(self.groupBox)
        self.month.setGeometry(QtCore.QRect(290, 240, 71, 31))
        self.month.setStyleSheet("background:white;\n""color:black;")
        self.month.setObjectName("month")
        self.year = QtWidgets.QLineEdit(self.groupBox)
        self.year.setGeometry(QtCore.QRect(190, 240, 81, 31))
        self.year.setStyleSheet("background:white;\n""color:black;")
        self.year.setObjectName("year")
        self.DOB = QtWidgets.QLabel(self.groupBox)
        self.DOB.setGeometry(QtCore.QRect(40, 240, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.DOB.setFont(font)
        self.DOB.setStyleSheet("color:white;")
        self.DOB.setObjectName("DOB")
        self.uname = QtWidgets.QLabel(self.groupBox)
        self.uname.setGeometry(QtCore.QRect(40, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.uname.setFont(font)
        self.uname.setStyleSheet("color:white;")
        self.uname.setObjectName("uname")
        self.passwd = QtWidgets.QLabel(self.groupBox)
        self.passwd.setGeometry(QtCore.QRect(40, 200, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.passwd.setFont(font)
        self.passwd.setStyleSheet("color:white;")
        self.passwd.setObjectName("passwd")
        self.lname = QtWidgets.QLineEdit(self.groupBox)
        self.lname.setGeometry(QtCore.QRect(520, 90, 151, 31))
        self.lname.setStyleSheet("background:white;\n""color:black;")
        self.lname.setObjectName("lname")
        self.lastname = QtWidgets.QLabel(self.groupBox)
        self.lastname.setGeometry(QtCore.QRect(380, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.lastname.setFont(font)
        self.lastname.setStyleSheet("color:white;")
        self.lastname.setObjectName("lastname")
        self.gender = QtWidgets.QLabel(self.groupBox)
        self.gender.setGeometry(QtCore.QRect(40, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.gender.setFont(font)
        self.gender.setStyleSheet("color:white;")
        self.gender.setObjectName("gender")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(190, 300, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:white;")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(290, 300, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:white;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.refer2 = QtWidgets.QPushButton(self.groupBox)
        self.refer2.setGeometry(QtCore.QRect(50, 430, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.refer2.setFont(font)
        self.refer2.setStyleSheet("background:red;\n""color:black;\n""")
        self.refer2.setObjectName("refer2")
        ##refer2 fxn#################################################<pshreyam>
        self.refer2.clicked.connect(self.refer2fxn)
        #############################################################
        self.stackedWidget.addWidget(self.Sign_up)
        self.Sign_in = QtWidgets.QWidget()
        self.Sign_in.setObjectName("Sign_in")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Sign_in)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 50, 521, 371))
        self.groupBox_2.setStyleSheet("background:black;\n""border-radius:20px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(200, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLabel(self.groupBox_2)
        self.user_name.setGeometry(QtCore.QRect(60, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("color:white;")
        self.user_name.setObjectName("user_name")
        self.uname_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.uname_2.setGeometry(QtCore.QRect(180, 80, 231, 41))
        self.uname_2.setStyleSheet("background:white;\n""color:black;\n""border-radius:20px;")
        self.uname_2.setObjectName("uname_2")
        self.pass_word = QtWidgets.QLabel(self.groupBox_2)
        self.pass_word.setGeometry(QtCore.QRect(60, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.pass_word.setFont(font)
        self.pass_word.setStyleSheet("color:white;")
        self.pass_word.setObjectName("pass_word")
        self.passwd_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwd_2.setGeometry(QtCore.QRect(180, 140, 231, 41))
        self.passwd_2.setStyleSheet("background:white;\n""color:black;\n""border-radius:20px;")
        self.passwd_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_2.setObjectName("passwd_2")
        self.login = QtWidgets.QPushButton(self.groupBox_2)
        self.login.setGeometry(QtCore.QRect(210, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setStyleSheet("background:green;\n""color:black;\n""border-radius:20px;")
        self.login.setObjectName("login")
        self.exit = QtWidgets.QPushButton(self.groupBox_2)
        self.exit.setGeometry(QtCore.QRect(340, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background:green;\n""color:black;\n""border-radius:20px;")
        self.exit.setObjectName("exit")
        self.refer = QtWidgets.QPushButton(self.Sign_in)
        self.refer.setGeometry(QtCore.QRect(400, 480, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.refer.setFont(font)
        self.refer.setStyleSheet("background:green;\n""color:black;\n""border-radius:20px;")
        self.refer.setObjectName("refer")
        ##refer fxn####################################################<pshreyam>
        self.refer.clicked.connect(self.referfxn)
        ################################################################
        self.stackedWidget.addWidget(self.Sign_in)
        Signup.setCentralWidget(self.Signup_2)
        self.menubar = QtWidgets.QMenuBar(Signup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Signup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Signup)
        self.statusbar.setObjectName("statusbar")
        Signup.setStatusBar(self.statusbar)

        self.retranslateUi(Signup)
        self.stackedWidget.setCurrentIndex(0)
        self.exit_2.clicked.connect(Signup.close)
        self.exit.clicked.connect(Signup.close)
        QtCore.QMetaObject.connectSlotsByName(Signup)

    def retranslateUi(self, Signup):
        _translate = QtCore.QCoreApplication.translate
        Signup.setWindowTitle(_translate("Signup", "Sign Up"))
        self.groupBox.setTitle(_translate("Signup", "Sign Up"))
        self.fullname.setText(_translate("Signup", "First Name"))
        self.signup.setText(_translate("Signup", "Signup"))
        self.exit_2.setText(_translate("Signup", "Exit"))
        self.checkBox.setText(_translate("Signup", "I agree to the all the terms and conditions."))
        self.repass.setText(_translate("Signup", "Re-password"))
        self.DOB.setText(_translate("Signup", "Date of Birth"))
        self.uname.setText(_translate("Signup", "Username"))
        self.passwd.setText(_translate("Signup", "Password"))
        self.lastname.setText(_translate("Signup", "Last Name"))
        self.gender.setText(_translate("Signup", "Gender"))
        self.radioButton.setText(_translate("Signup", "Male"))
        self.radioButton_2.setText(_translate("Signup", "Female"))
        self.refer2.setText(_translate("Signup", "Sign in?"))
        self.label.setText(_translate("Signup", "Login"))
        self.user_name.setText(_translate("Signup", "Username"))
        self.pass_word.setText(_translate("Signup", "Password"))
        self.login.setText(_translate("Signup", "Login"))
        self.exit.setText(_translate("Signup", "Exit"))
        self.refer.setText(_translate("Signup", "Or Sign Up?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signup = QtWidgets.QMainWindow()
    ui = Ui_Signup()
    ui.setupUi(Signup)
    Signup.show()
    sys.exit(app.exec_())
