# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deathregistrationform.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import datetime
import nepali_date
import sw_string

table="DeathRegistration"


class Ui_Deathform(object):
    def setupUi(self, Deathform):
        Deathform.setObjectName("Deathform")
        Deathform.resize(694, 801)
        self.centralwidget = QtWidgets.QWidget(Deathform)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 1119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.districtLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel_2.setObjectName("districtLabel_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.districtLabel_2)
        self.districtLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit_2.setObjectName("districtLineEdit_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit_2)
        self.municipalityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.municipalityLabel.setObjectName("municipalityLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.municipalityLabel)
        self.municipalityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.municipalityLineEdit.setObjectName("municipalityLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.municipalityLineEdit)
        self.wardNoLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.wardNoLabel_2.setObjectName("wardNoLabel_2")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel_2)
        self.roadtLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roadtLabel.setObjectName("roadtLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.roadtLabel)
        self.roadStreetLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.roadStreetLineEdit.setObjectName("roadStreetLineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.roadStreetLineEdit)
        self.houseNoLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.houseNoLabel_2.setObjectName("houseNoLabel_2")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.houseNoLabel_2)
        self.houseNoLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.houseNoLineEdit_2.setObjectName("houseNoLineEdit_2")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.houseNoLineEdit_2)
        self.villageLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.villageLabel_2.setObjectName("villageLabel_2")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.villageLabel_2)
        self.villageCommunityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.villageCommunityLineEdit.setObjectName("villageCommunityLineEdit")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.villageCommunityLineEdit)
        self.wardNoLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.wardNoLineEdit_2.setObjectName("wardNoLineEdit_2")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wardNoLineEdit_2)
        self.gridLayout_2.addLayout(self.formLayout_5, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.districtLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel.setObjectName("districtLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.districtLabel)
        self.districtLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit.setObjectName("districtLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit)
        self.mubicipalityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mubicipalityLabel.setObjectName("mubicipalityLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mubicipalityLabel)
        self.mubicipalityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mubicipalityLineEdit.setObjectName("mubicipalityLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mubicipalityLineEdit)
        self.wardNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.wardNoLabel.setObjectName("wardNoLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel)
        self.wardNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.wardNoLineEdit.setObjectName("wardNoLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wardNoLineEdit)
        self.roadLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roadLabel.setObjectName("roadLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.roadLabel)
        self.roadLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.roadLineEdit.setObjectName("roadLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.roadLineEdit)
        self.houseNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.houseNoLabel.setObjectName("houseNoLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.houseNoLabel)
        self.houseNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.houseNoLineEdit.setObjectName("houseNoLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.houseNoLineEdit)
        self.villageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.villageLabel.setObjectName("villageLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.villageLabel)
        self.villageLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.villageLineEdit.setObjectName("villageLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.villageLineEdit)
        self.gridLayout_2.addLayout(self.formLayout_2, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.birthRegistrationNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.birthRegistrationNoLabel.setObjectName("birthRegistrationNoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.birthRegistrationNoLabel)
        self.birthRegistrationNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.birthRegistrationNoLineEdit.setObjectName("birthRegistrationNoLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.birthRegistrationNoLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.dateOfBirthLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateOfBirthLabel.setObjectName("dateOfBirthLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateOfBirthLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.dateOfDeathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateOfDeathLabel.setObjectName("dateOfDeathLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dateOfDeathLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_2.addWidget(self.dateEdit_3)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.placeOfDeathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.placeOfDeathLabel.setObjectName("placeOfDeathLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.placeOfDeathLabel)
        self.placeOfDeathLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.placeOfDeathLineEdit.setObjectName("placeOfDeathLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.placeOfDeathLineEdit)
        self.gridLayout_2.addLayout(self.formLayout, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 1)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.citizenshipNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.citizenshipNoLabel.setObjectName("citizenshipNoLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.citizenshipNoLabel)
        self.citizenshipNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.citizenshipNoLineEdit.setObjectName("citizenshipNoLineEdit")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.citizenshipNoLineEdit)
        self.issueDistrictLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.issueDistrictLabel.setObjectName("issueDistrictLabel")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.issueDistrictLabel)
        self.issueDistrictLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.issueDistrictLineEdit.setObjectName("issueDistrictLineEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.issueDistrictLineEdit)
        self.issueDateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.issueDateLabel.setObjectName("issueDateLabel")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.issueDateLabel)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_5)
        self.forForeignerLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.forForeignerLabel.setObjectName("forForeignerLabel")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.forForeignerLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.formLayout_6.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.qualificationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.qualificationLabel.setObjectName("qualificationLabel")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.qualificationLabel)
        self.qualificationLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.qualificationLineEdit.setObjectName("qualificationLineEdit")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.qualificationLineEdit)
        self.mothersTongueLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mothersTongueLabel.setObjectName("mothersTongueLabel")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mothersTongueLabel)
        self.mothersTongueLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mothersTongueLineEdit.setObjectName("mothersTongueLineEdit")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mothersTongueLineEdit)
        self.casteLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.casteLabel.setObjectName("casteLabel")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.casteLabel)
        self.casteLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.casteLineEdit.setObjectName("casteLineEdit")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.casteLineEdit)
        self.religionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.religionLabel.setObjectName("religionLabel")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.religionLabel)
        self.religionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.religionLineEdit.setObjectName("religionLineEdit")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.religionLineEdit)
        self.grandFatherLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.grandFatherLabel.setObjectName("grandFatherLabel")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.grandFatherLabel)
        self.grandFatherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.grandFatherLineEdit.setObjectName("grandFatherLineEdit")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.grandFatherLineEdit)
        self.fatherLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fatherLabel.setObjectName("fatherLabel")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.fatherLabel)
        self.fatherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fatherLineEdit.setObjectName("fatherLineEdit")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fatherLineEdit)
        self.motherLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.motherLabel.setObjectName("motherLabel")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.motherLabel)
        self.motherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.motherLineEdit.setObjectName("motherLineEdit")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.motherLineEdit)
        self.spouseLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.spouseLabel.setObjectName("spouseLabel")
        self.formLayout_6.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.spouseLabel)
        self.spouseLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.spouseLineEdit.setObjectName("spouseLineEdit")
        self.formLayout_6.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.spouseLineEdit)
        self.causeOfDeathLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.causeOfDeathLabel.setObjectName("causeOfDeathLabel")
        self.formLayout_6.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.causeOfDeathLabel)
        self.causeOfDeathLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.causeOfDeathLineEdit.setObjectName("causeOfDeathLineEdit")
        self.formLayout_6.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.causeOfDeathLineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_6.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.gridLayout_2.addLayout(self.formLayout_6, 8, 0, 1, 1)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.registrationNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.registrationNoLabel.setObjectName("registrationNoLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.registrationNoLabel)
        self.registrationNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.registrationNoLineEdit.setObjectName("registrationNoLineEdit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.registrationNoLineEdit)
        self.gridLayout_2.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        Deathform.setCentralWidget(self.centralwidget)

        self.retranslateUi(Deathform)
        QtCore.QMetaObject.connectSlotsByName(Deathform)

    def retranslateUi(self, Deathform):
        _translate = QtCore.QCoreApplication.translate
        Deathform.setWindowTitle(_translate("Deathform", "MainWindow"))
        self.districtLabel_2.setText(_translate("Deathform", "District"))
        self.municipalityLabel.setText(_translate("Deathform", "Municipality"))
        self.wardNoLabel_2.setText(_translate("Deathform", "Ward No"))
        self.roadtLabel.setText(_translate("Deathform", "Road/street"))
        self.houseNoLabel_2.setText(_translate("Deathform", "House No"))
        self.villageLabel_2.setText(_translate("Deathform", "Village/Community"))
        self.label_3.setText(_translate("Deathform", "Adress Of Deceased"))
        self.label.setText(_translate("Deathform", "Details Of Deceased\'s"))
        self.districtLabel.setText(_translate("Deathform", "District"))
        self.mubicipalityLabel.setText(_translate("Deathform", "Municopality"))
        self.wardNoLabel.setText(_translate("Deathform", "Ward No"))
        self.roadLabel.setText(_translate("Deathform", "Road/Route/street"))
        self.houseNoLabel.setText(_translate("Deathform", "House No:"))
        self.villageLabel.setText(_translate("Deathform", "Village/Community"))
        self.label_2.setText(_translate("Deathform", "Place Of Birth"))
        self.birthRegistrationNoLabel.setText(_translate("Deathform", "Birth Registration No"))
        self.nameLabel.setText(_translate("Deathform", "Name"))
        self.dateOfBirthLabel.setText(_translate("Deathform", "Date Of Birth"))
        self.dateOfDeathLabel.setText(_translate("Deathform", "Date Of Death"))
        self.placeOfDeathLabel.setText(_translate("Deathform", "Place of Death"))
        self.label_4.setText(_translate("Deathform", "Deatils Of Deceased"))
        self.citizenshipNoLabel.setText(_translate("Deathform", "Citizenship No"))
        self.issueDistrictLabel.setText(_translate("Deathform", "Issue District"))
        self.issueDateLabel.setText(_translate("Deathform", "Issue Date"))
        self.forForeignerLabel.setText(_translate("Deathform", "For Foreigner"))
        self.lineEdit_2.setPlaceholderText(_translate("Deathform", "Country"))
        self.lineEdit.setPlaceholderText(_translate("Deathform", "Passport No"))
        self.qualificationLabel.setText(_translate("Deathform", "Qualification"))
        self.mothersTongueLabel.setText(_translate("Deathform", "Mothers Tongue"))
        self.casteLabel.setText(_translate("Deathform", "Caste"))
        self.religionLabel.setText(_translate("Deathform", "Religion"))
        self.grandFatherLabel.setText(_translate("Deathform", "GrandFather"))
        self.fatherLabel.setText(_translate("Deathform", "Father"))
        self.motherLabel.setText(_translate("Deathform", "Mother"))
        self.spouseLabel.setText(_translate("Deathform", "Spouse"))
        self.causeOfDeathLabel.setText(_translate("Deathform", "Cause Of Death"))
        self.registrationNoLabel.setText(_translate("Deathform", "Registration No"))
class ActualWork():
    def __init__(self):
        import dbconnect
        self.db=dbconnect.database_wardwindow("localhost","root")
        self.deathForm = QtWidgets.QMainWindow()
        self.ui = Ui_Deathform()
        self.ui.setupUi(self.deathForm)
        self.deathForm.show()
        self.actualWork()

    def actualWork(self):
        self.ui.buttonBox.accepted.connect(self.submitform)
        self.ui.buttonBox.rejected.connect(lambda:self.deathForm.close())

    def submitform(self):
        self.values=self.getallvalues()
        a=sw_string.generateList(**self.values)
        #a=["RegDate","1","RegNo","2","C","3","D","4","E","5"]
        #b=['RegNo','123-32','detailsofmarriage', "('Social Tradition', ('2000-01-01', '2056/09/17'))", 'locationofmarriage', "('Kavre', 'Namobudda', '04', 'Timal Road', 'Methinkot', '45', '')", 'detailsofspouse', "{'detailsofbride': ('Tandon', 'Rabina', '2057/01/05', 'Kami', '+2', 'Actress', 'Divorcee', ('Rampur', 'Narayanghat', '5', 'Ghandi Street', 'Hariharpur', '78', 'India'), ('India', '27-12398721', '2071/06/09', 'Rampur', '87289398', 'India', 'New Delhi'), ('Fariha Tandon', 'Kanod Tandon', 'Kajol Tandon')), 'detailsofbridegroom': ('Ghimere', 'Tilak', '2051/03/21', 'Brahmin', 'B.Sc.', 'Astrologer', 'Single', ('Solukhumbu', 'Namche Bazar', '9', 'Manila Street', 'Vaisepati', '567', 'Nepal'), ('Nepal', '983-3468', '2067/03/05', 'Solukhumbu', '', '', ''), ('Goshnath Ghimere', 'Farilal Ghimere', 'Nabina Ghimere'))}"]
        #a=['RegDate',,b[0],b[1],b[2],b[3].replace("'","__"),b[4],b[5].replace("'","__"),b[6],b[7].replace("'","__")]
        #print(a)
        self.db.createFormTable(table)
        self.db.addColumns(table,a[4],a[6],a[8])
        self.db.insertValues(table,a)
    def getallvalues(self):
        #print('i love you')
        self.deathRegNo=self.ui.registrationNoLineEdit.text()
        date=QDate(self.ui.dateEdit.date())
        year,month,day=date.getDate()
        birth_in_ad=datetime.date(year,month,day)
        birth_in_bs=nepali_date.NepaliDate.to_nepali_date(birth_in_ad)
        today=nepali_date.NepaliDate.today()
        registrationdate=str(today)[3:]
        self.birthdate=(str(birth_in_ad),str(birth_in_bs)[3:])
        date=QDate(self.ui.dateEdit_3.date())
        year,month,day=date.getDate()
        death_in_ad=datetime.date(year,month,day)
        death_in_bs=nepali_date.NepaliDate.to_nepali_date(death_in_ad)
        self.deathdate=(str(death_in_ad),str(death_in_bs)[3:])
        detailsofdeceased=(self.birthdate,self.deathdate,self.ui.birthRegistrationNoLineEdit.text(),self.ui.nameLineEdit.text(),self.ui.placeOfDeathLineEdit.text())
        placeofbirth=(self.ui.districtLineEdit.text(),self.ui.mubicipalityLineEdit.text(),self.ui.wardNoLineEdit.text(),self.ui.roadLineEdit.text(),self.ui.houseNoLineEdit.text(),self.ui.villageLineEdit.text())
        Adressofdeceased=(self.ui.districtLineEdit_2.text(),self.ui.municipalityLineEdit.text(),self.ui.wardNoLineEdit_2.text(),self.ui.roadStreetLineEdit.text(),self.ui.houseNoLineEdit_2.text(),self.ui.houseNoLineEdit_3.text())
        date=QDate(self.ui.dateEdit_5.date())
        year,month,day=date.getDate()
        issue_in_ad=datetime.date(year,month,day)
        issue_in_bs=nepali_date.NepaliDate.to_nepali_date(issue_in_ad)
        self.issuedate=(str(issue_in_ad),str(issue_in_bs)[3:])
        briefofdeath=(self.issuedate,self.ui.citizenshipNoLineEdit.text(),self.ui.issueDistrictLineEdit.text(),self.ui.lineEdit_2.text(),self.ui.lineEdit.text(),self.ui.qualificationLineEdit.text(),self.ui.mothersTongueLineEdit.text(),self.ui.casteLineEdit.text(),self.ui.religionLineEdit.text(),self.ui.grandFatherLineEdit.text(),self.ui.fatherLineEdit.text(),self.ui.motherLineEdit.text(),self.ui.spouseLineEdit.text(),self.ui.causeOfDeathLineEdit.text())
        return {"RegDate":registrationdate,"RegNo":self.deathRegNo,"detaillsofdeceased":str(detailsofdeceased) , "placeofbirth":str(placeofbirth) , 'adressofdecesed':str(Adressofdeceased),'briefofdeath':str(briefofdeath)}

    
    def closeActualWork(self):
        self.deathForm.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aw=ActualWork()
    '''
    Deathform = QtWidgets.QMainWindow()
    ui = Ui_Deathform()
    ui.setupUi(Deathform)
    Deathform.show()
    '''
    sys.exit(app.exec_())
