from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import datetime
import nepali_date
import sw_string

table="DivorceRegistration"


class Ui_DivorceForm(object):
    def setupUi(self, DivorceForm):
        DivorceForm.setObjectName("DivorceForm")
        DivorceForm.resize(824, 812)
        self.centralwidget = QtWidgets.QWidget(DivorceForm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 787, 1077))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.nameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.lastnameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastnameLabel.setObjectName("lastnameLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lastnameLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.fullNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fullNameLabel.setObjectName("fullNameLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fullNameLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.dateOfBirthLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateOfBirthLabel.setObjectName("dateOfBirthLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.dateOfBirthLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_6.addWidget(self.dateEdit_2)
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.birthRegistrationNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.birthRegistrationNoLabel.setObjectName("birthRegistrationNoLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.birthRegistrationNoLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_7.addWidget(self.lineEdit_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.casteLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.casteLabel.setObjectName("casteLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.casteLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_8.addWidget(self.lineEdit_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_8.addWidget(self.lineEdit_9)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.countryWhereBornLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.countryWhereBornLabel.setObjectName("countryWhereBornLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.countryWhereBornLabel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_9.addWidget(self.lineEdit_12)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_9.addWidget(self.lineEdit_11)
        self.formLayout_2.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.citizenshipNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.citizenshipNoLabel.setObjectName("citizenshipNoLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.citizenshipNoLabel)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_10.addWidget(self.lineEdit_14)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_10.addWidget(self.lineEdit_13)
        self.formLayout_2.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.issueDistrictLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.issueDistrictLabel.setObjectName("issueDistrictLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.issueDistrictLabel)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_11.addWidget(self.lineEdit_16)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_11.addWidget(self.lineEdit_15)
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.issueDateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.issueDateLabel.setObjectName("issueDateLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.issueDateLabel)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.horizontalLayout_12.addWidget(self.dateEdit_4)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_12.addWidget(self.dateEdit_3)
        self.formLayout_2.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.passportNoIfFireignLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.passportNoIfFireignLabel.setObjectName("passportNoIfFireignLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.passportNoIfFireignLabel)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_13.addWidget(self.lineEdit_18)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_13.addWidget(self.lineEdit_17)
        self.formLayout_2.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.issueDateLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.issueDateLabel_2.setObjectName("issueDateLabel_2")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.issueDateLabel_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.dateEdit_8 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.horizontalLayout_16.addWidget(self.dateEdit_8)
        self.dateEdit_7 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.horizontalLayout_16.addWidget(self.dateEdit_7)
        self.formLayout_2.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.adressBeforeRelationSeparationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.adressBeforeRelationSeparationLabel.setObjectName("adressBeforeRelationSeparationLabel")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.adressBeforeRelationSeparationLabel)
        self.districtLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel_2.setObjectName("districtLabel_2")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.districtLabel_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_17.addWidget(self.lineEdit_20)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_17.addWidget(self.lineEdit_19)
        self.formLayout_2.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.municipalityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.municipalityLabel.setObjectName("municipalityLabel")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.municipalityLabel)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_15.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_15.addWidget(self.lineEdit_22)
        self.formLayout_2.setLayout(15, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.wardNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.wardNoLabel.setObjectName("wardNoLabel")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_18.addWidget(self.lineEdit_24)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_18.addWidget(self.lineEdit_23)
        self.formLayout_2.setLayout(16, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.roadLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roadLabel.setObjectName("roadLabel")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.roadLabel)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_19.addWidget(self.lineEdit_26)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_19.addWidget(self.lineEdit_25)
        self.formLayout_2.setLayout(17, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.villageCommunityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.villageCommunityLabel.setObjectName("villageCommunityLabel")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.villageCommunityLabel)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_20.addWidget(self.lineEdit_28)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_20.addWidget(self.lineEdit_27)
        self.formLayout_2.setLayout(18, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.houseNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.houseNoLabel.setObjectName("houseNoLabel")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.houseNoLabel)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_21.addWidget(self.lineEdit_30)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_21.addWidget(self.lineEdit_29)
        self.formLayout_2.setLayout(19, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.qualificationLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.qualificationLabel.setObjectName("qualificationLabel")
        self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.qualificationLabel)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_22.addWidget(self.lineEdit_33)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_22.addWidget(self.lineEdit_31)
        self.formLayout_2.setLayout(20, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.religionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.religionLabel.setObjectName("religionLabel")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.religionLabel)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_23.addWidget(self.lineEdit_34)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_23.addWidget(self.lineEdit_32)
        self.formLayout_2.setLayout(21, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_23)
        self.motherTongueLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.motherTongueLabel.setObjectName("motherTongueLabel")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.motherTongueLabel)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_24.addWidget(self.lineEdit_36)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_24.addWidget(self.lineEdit_35)
        self.formLayout_2.setLayout(22, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_24)
        self.grandFatherNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.grandFatherNameLabel.setObjectName("grandFatherNameLabel")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.grandFatherNameLabel)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_25.addWidget(self.lineEdit_38)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.horizontalLayout_25.addWidget(self.lineEdit_37)
        self.formLayout_2.setLayout(23, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_25)
        self.fatherNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fatherNameLabel.setObjectName("fatherNameLabel")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.fatherNameLabel)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_26.addWidget(self.lineEdit_40)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_26.addWidget(self.lineEdit_39)
        self.formLayout_2.setLayout(24, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_26)
        self.motherNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.motherNameLabel.setObjectName("motherNameLabel")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.motherNameLabel)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.horizontalLayout_27.addWidget(self.lineEdit_42)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_27.addWidget(self.lineEdit_41)
        self.formLayout_2.setLayout(25, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_27)
        self.marriageDateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.marriageDateLabel.setObjectName("marriageDateLabel")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.marriageDateLabel)
        self.numberOfChildrenLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.numberOfChildrenLabel.setObjectName("numberOfChildrenLabel")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.numberOfChildrenLabel)
        self.numberOfChildrenLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.numberOfChildrenLineEdit.setObjectName("numberOfChildrenLineEdit")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.numberOfChildrenLineEdit)
        self.totalAliveChildrenLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.totalAliveChildrenLabel.setObjectName("totalAliveChildrenLabel")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.LabelRole, self.totalAliveChildrenLabel)
        self.totalAliveChildrenLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.totalAliveChildrenLineEdit.setObjectName("totalAliveChildrenLineEdit")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.FieldRole, self.totalAliveChildrenLineEdit)
        self.numberOfChildrenLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.numberOfChildrenLabel_2.setObjectName("numberOfChildrenLabel_2")
        self.formLayout_2.setWidget(29, QtWidgets.QFormLayout.LabelRole, self.numberOfChildrenLabel_2)
        self.sonLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sonLabel.setObjectName("sonLabel")
        self.formLayout_2.setWidget(30, QtWidgets.QFormLayout.LabelRole, self.sonLabel)
        self.daughterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.daughterLabel.setObjectName("daughterLabel")
        self.formLayout_2.setWidget(31, QtWidgets.QFormLayout.LabelRole, self.daughterLabel)
        self.numberOfChildrenLivingWithOtherLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.numberOfChildrenLivingWithOtherLabel.setObjectName("numberOfChildrenLivingWithOtherLabel")
        self.formLayout_2.setWidget(32, QtWidgets.QFormLayout.LabelRole, self.numberOfChildrenLivingWithOtherLabel)
        self.numberOfChildrenLivingWithOtherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.numberOfChildrenLivingWithOtherLineEdit.setObjectName("numberOfChildrenLivingWithOtherLineEdit")
        self.formLayout_2.setWidget(32, QtWidgets.QFormLayout.FieldRole, self.numberOfChildrenLivingWithOtherLineEdit)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.horizontalLayout_28.addWidget(self.dateEdit_6)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.horizontalLayout_28.addWidget(self.dateEdit_5)
        self.formLayout_2.setLayout(26, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.horizontalLayout_30.addWidget(self.lineEdit_46)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.horizontalLayout_30.addWidget(self.lineEdit_45)
        self.formLayout_2.setLayout(30, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.horizontalLayout_31.addWidget(self.lineEdit_44)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.horizontalLayout_31.addWidget(self.lineEdit_43)
        self.formLayout_2.setLayout(31, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_31)
        self.gridLayout_2.addLayout(self.formLayout_2, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.TypeOfCourtLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TypeOfCourtLabel.setObjectName("TypeOfCourtLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.TypeOfCourtLabel)
        self.TypeOfCourtLineEdit = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.TypeOfCourtLineEdit.setObjectName("TypeOfCourtLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TypeOfCourtLineEdit)
        self.districtLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel.setObjectName("districtLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.districtLabel)
        self.districtLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit.setObjectName("districtLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit)
        self.courtDecisionNumberLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.courtDecisionNumberLabel.setObjectName("courtDecisionNumberLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.courtDecisionNumberLabel)
        self.courtDecisionNumberLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.courtDecisionNumberLineEdit.setObjectName("courtDecisionNumberLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.courtDecisionNumberLineEdit)
        self.courtDecisionDateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.courtDecisionDateLabel.setObjectName("courtDecisionDateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.courtDecisionDateLabel)
        self.courtDecisionDateDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.courtDecisionDateDateEdit.setObjectName("courtDecisionDateDateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.courtDecisionDateDateEdit)
        self.marriageRegistrationNumberLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.marriageRegistrationNumberLabel.setObjectName("marriageRegistrationNumberLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.marriageRegistrationNumberLabel)
        self.marriageRegistrationNumberLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.marriageRegistrationNumberLineEdit.setObjectName("marriageRegistrationNumberLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.marriageRegistrationNumberLineEdit)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        DivorceForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(DivorceForm)
        QtCore.QMetaObject.connectSlotsByName(DivorceForm)

    def retranslateUi(self, DivorceForm):
        _translate = QtCore.QCoreApplication.translate
        DivorceForm.setWindowTitle(_translate("DivorceForm", "Divorce Registration"))
        self.label.setText(_translate("DivorceForm", "<b>Details Regarding The Separation</b>"))
        self.label_2.setText(_translate("DivorceForm", "<b>Details Of Wife And Husband</b>"))
        self.Label.setText(_translate("DivorceForm", "....."))
        self.label_4.setText(_translate("DivorceForm", "Husband Details"))
        self.label_3.setText(_translate("DivorceForm", "Wife Details"))
        self.nameLabel.setText(_translate("DivorceForm", "Name"))
        self.lastnameLabel.setText(_translate("DivorceForm", "Lastname"))
        self.fullNameLabel.setText(_translate("DivorceForm", "Full Name"))
        self.dateOfBirthLabel.setText(_translate("DivorceForm", "Date Of Birth"))
        self.birthRegistrationNoLabel.setText(_translate("DivorceForm", "<b>Divorce Registration No.</b>"))
        self.casteLabel.setText(_translate("DivorceForm", "Caste"))
        self.countryWhereBornLabel.setText(_translate("DivorceForm", "Country Where Born"))
        self.citizenshipNoLabel.setText(_translate("DivorceForm", "Citizenship No(if have)"))
        self.issueDistrictLabel.setText(_translate("DivorceForm", "Issue District"))
        self.issueDateLabel.setText(_translate("DivorceForm", "Issue Date"))
        self.passportNoIfFireignLabel.setText(_translate("DivorceForm", "Passport No. (for foreign citizen)"))
        self.issueDateLabel_2.setText(_translate("DivorceForm", "Issue Date"))
        self.adressBeforeRelationSeparationLabel.setText(_translate("DivorceForm", "<b>Adress Before Relation Separation</b>"))
        self.districtLabel_2.setText(_translate("DivorceForm", "District"))
        self.municipalityLabel.setText(_translate("DivorceForm", "Municipality/VDC"))
        self.wardNoLabel.setText(_translate("DivorceForm", "Ward No."))
        self.roadLabel.setText(_translate("DivorceForm", "Road/Street"))
        self.villageCommunityLabel.setText(_translate("DivorceForm", "Village/Community"))
        self.houseNoLabel.setText(_translate("DivorceForm", "House No."))
        self.qualificationLabel.setText(_translate("DivorceForm", "Qualification"))
        self.religionLabel.setText(_translate("DivorceForm", "Religion"))
        self.motherTongueLabel.setText(_translate("DivorceForm", "Mother Tongue"))
        self.grandFatherNameLabel.setText(_translate("DivorceForm", "Grandfather\'s Name"))
        self.fatherNameLabel.setText(_translate("DivorceForm", "Father\'s Name"))
        self.motherNameLabel.setText(_translate("DivorceForm", "Mother\'s Name"))
        self.marriageDateLabel.setText(_translate("DivorceForm", "Marriage Date"))
        self.numberOfChildrenLabel.setText(_translate("DivorceForm", "Number of children"))
        self.totalAliveChildrenLabel.setText(_translate("DivorceForm", "Total alive children"))
        self.numberOfChildrenLabel_2.setText(_translate("DivorceForm", "<b>Number Of children with parent</b>"))
        self.sonLabel.setText(_translate("DivorceForm", "Son"))
        self.daughterLabel.setText(_translate("DivorceForm", "Daughter"))
        self.numberOfChildrenLivingWithOtherLabel.setText(_translate("DivorceForm", "Number of children living with other"))
        self.TypeOfCourtLabel.setText(_translate("DivorceForm", "The type of court that decides separation"))
        self.districtLabel.setText(_translate("DivorceForm", "District"))
        self.courtDecisionNumberLabel.setText(_translate("DivorceForm", "Court decision number"))
        self.courtDecisionDateLabel.setText(_translate("DivorceForm", "Court decision date"))
        self.marriageRegistrationNumberLabel.setText(_translate("DivorceForm", "Marriage Registration number"))

class ActualWork():
    def __init__(self):
        import dbconnect
        self.db=dbconnect.database_wardwindow("localhost","root")
        self.DivorceForm = QtWidgets.QMainWindow()
        self.ui = Ui_DivorceForm()
        self.ui.setupUi(self.DivorceForm)
        self.DivorceForm.show()
        self.actualWork()

    def actualWork(self):
        self.ui.buttonBox.accepted.connect(self.submitform)
        self.ui.buttonBox.rejected.connect(lambda:self.DivorceForm.close())

    def submitform(self):
        self.values=self.getallvalues()
        a=sw_string.generateList(**self.values)
        #a=["RegDate","1","RegNo","2","C","3","D","4","E","5"]
        #b=['RegNo','123-32','detailsofmarriage', "('Social Tradition', ('2000-01-01', '2056/09/17'))", 'locationofmarriage', "('Kavre', 'Namobudda', '04', 'Timal Road', 'Methinkot', '45', '')", 'detailsofspouse', "{'detailsofbride': ('Tandon', 'Rabina', '2057/01/05', 'Kami', '+2', 'Actress', 'Divorcee', ('Rampur', 'Narayanghat', '5', 'Ghandi Street', 'Hariharpur', '78', 'India'), ('India', '27-12398721', '2071/06/09', 'Rampur', '87289398', 'India', 'New Delhi'), ('Fariha Tandon', 'Kanod Tandon', 'Kajol Tandon')), 'detailsofbridegroom': ('Ghimere', 'Tilak', '2051/03/21', 'Brahmin', 'B.Sc.', 'Astrologer', 'Single', ('Solukhumbu', 'Namche Bazar', '9', 'Manila Street', 'Vaisepati', '567', 'Nepal'), ('Nepal', '983-3468', '2067/03/05', 'Solukhumbu', '', '', ''), ('Goshnath Ghimere', 'Farilal Ghimere', 'Nabina Ghimere'))}"]
        #a=['RegDate',,b[0],b[1],b[2],b[3].replace("'","__"),b[4],b[5].replace("'","__"),b[6],b[7].replace("'","__")]
        #print(a)
        self.db.createFormTable(table)
        self.db.addColumns(table,a[4],a[6],a[8])
        self.db.insertValues(table,a)

    def getallvalues(self):
        '''
        self.birthRegNo=self.ui.birthRegistrationNoLineEdit.text()
        #self.marriagetype=self.ui.marriageTypeComboBox.currentText()
        date=QDate(self.ui.dateOfBirthDateEdit.date())
        year,month,day=date.getDate()
        birth_in_ad=datetime.date(year,month,day)
        birth_in_bs=nepali_date.NepaliDate.to_nepali_date(birth_in_ad)
        today=nepali_date.NepaliDate.today()
        registrationdate=str(today)[3:]
        self.birthdate=(str(birth_in_ad),str(birth_in_bs)[3:])
        detailsofbirth=(self.birthdate,self.ui.nameLineEdit.text(),self.ui.placeOfBirthComboBox.currentText(),self.ui.genderComboBox.currentText(),self.ui.casteLineEdit.text(),self.ui.birthTypeComboBox.currentText(),self.ui.physicalDisabledLineEdit.text())
        locationofbirth=(self.ui.districtLineEdit.text(),self.ui.MunicipalityLineEdit.text(),self.ui.wardNoLineEdit.text(),self.ui.countryIfBornInForeignLineEdit.text())
        self.detailsoffather=(self.ui.lineEdit.text(),self.ui.districtLineEdit_3.text(),self.ui.districtLineEdit_4.text(),self.ui.districtLineEdit_6.text(),self.ui.districtLineEdit_8.text(),self.ui.districtLineEdit_10.text(),self.ui.districtLineEdit_12.text(),self.ui.districtLineEdit_14.text(),self.ui.districtLineEdit_16.text(),self.ui.districtLineEdit_18.text(),self.ui.districtLineEdit_20.text(),self.ui.districtLineEdit_22.text(),self.ui.districtLineEdit_24.text(),self.ui.districtLineEdit_26.text(),self.ui.districtLineEdit_28.text(),self.ui.districtLineEdit_30.text(),self.ui.districtLineEdit_32.text(),self.ui.districtLineEdit_34.text())
        self.detailsofmother=(self.ui.lineEdit_6.text(),self.ui.districtLineEdit_2.text(),self.ui.districtLineEdit_5.text(),self.ui.districtLineEdit_7.text(),self.ui.districtLineEdit_9.text(),self.ui.districtLineEdit_11.text(),self.ui.districtLineEdit_13.text(),self.ui.districtLineEdit_15.text(),self.ui.districtLineEdit_17.text(),self.ui.districtLineEdit_19.text(),self.ui.districtLineEdit_21.text(),self.ui.districtLineEdit_23.text(),self.ui.districtLineEdit_25.text(),self.ui.districtLineEdit_27.text(),self.ui.districtLineEdit_29.text(),self.ui.districtLineEdit_31.text(),self.ui.districtLineEdit_33.text(),self.ui.districtLineEdit_35.text())        
        date1=QDate(self.ui.dateEdit_2.date())
        year,month,day=date1.getDate()
        self.marriage_in_ad1=datetime.date1(year,month,day)
        date2=QDate(self.ui.dateEdit.date())
        year,month,day=date2.getDate()
        marriage_in_ad2=datetime.date2(year,month,day)
        self.marriage_in_bs=nepali_date.NepaliDate.to_nepali_date(birth_in_ad)
        detailsofparent=(self.ui.totalChildrenLineEdit.text(),self.ui.totalChildrenAliveLineEdit.text(),self.ui.marriageRegistrationNoLineEdit.text(),self.marriage_in_ad1,self.marriage_in_bs,self.detailsoffather,self.detailsofmother)
        return {"RegDate":registrationdate,"RegNo":self.birthRegNo,"detailsofbirth":str(detailsofbirth) , "locationofbirth":str(locationofbirth) , 'detailsofparent':str(detailsofparent)}
        '''
        pass
    
    def closeActualWork(self):
        self.DivorceForm.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aw=ActualWork()
    
    sys.exit(app.exec_())

