# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basaisarai.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 755, 582))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.registrationNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.registrationNoLabel.setObjectName("registrationNoLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.registrationNoLabel)
        self.registrationNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.registrationNoLineEdit.setObjectName("registrationNoLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.registrationNoLineEdit)
        self.districtLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel_2.setObjectName("districtLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.districtLabel_2)
        self.districtLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit_2.setObjectName("districtLineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit_2)
        self.municipalityLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.municipalityLabel_2.setObjectName("municipalityLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.municipalityLabel_2)
        self.municipalityLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.municipalityLineEdit_2.setObjectName("municipalityLineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.municipalityLineEdit_2)
        self.wardNoLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.wardNoLabel_2.setObjectName("wardNoLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel_2)
        self.wardNoLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.wardNoLineEdit_2.setObjectName("wardNoLineEdit_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wardNoLineEdit_2)
        self.roadStreetLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roadStreetLabel_2.setObjectName("roadStreetLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.roadStreetLabel_2)
        self.roadStreetLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.roadStreetLineEdit_2.setObjectName("roadStreetLineEdit_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.roadStreetLineEdit_2)
        self.houseNoLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.houseNoLabel_2.setObjectName("houseNoLabel_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.houseNoLabel_2)
        self.houseNoLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.houseNoLineEdit_2.setObjectName("houseNoLineEdit_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.houseNoLineEdit_2)
        self.villageCommunityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.villageCommunityLabel.setObjectName("villageCommunityLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.villageCommunityLabel)
        self.villageCommunityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.villageCommunityLineEdit.setObjectName("villageCommunityLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.villageCommunityLineEdit)
        self.nameOfHomeownerWhoRelocatedLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameOfHomeownerWhoRelocatedLabel.setObjectName("nameOfHomeownerWhoRelocatedLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.nameOfHomeownerWhoRelocatedLabel)
        self.nameOfHomeownerWhoRelocatedLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameOfHomeownerWhoRelocatedLineEdit.setObjectName("nameOfHomeownerWhoRelocatedLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.nameOfHomeownerWhoRelocatedLineEdit)
        self.dateOfRelocatedLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateOfRelocatedLabel.setObjectName("dateOfRelocatedLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.dateOfRelocatedLabel)
        self.dateOfRelocatedDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateOfRelocatedDateEdit.setObjectName("dateOfRelocatedDateEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dateOfRelocatedDateEdit)
        self.reasonOfRelocatedLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.reasonOfRelocatedLabel.setObjectName("reasonOfRelocatedLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.reasonOfRelocatedLabel)
        self.reasonOfRelocatedComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.reasonOfRelocatedComboBox.setObjectName("reasonOfRelocatedComboBox")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.reasonOfRelocatedComboBox)
        self.gridLayout_2.addLayout(self.formLayout_2, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.districtLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.districtLabel.setObjectName("districtLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.districtLabel)
        self.districtLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit.setObjectName("districtLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit)
        self.municipalityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.municipalityLabel.setObjectName("municipalityLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.municipalityLabel)
        self.municipalityLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.municipalityLineEdit.setObjectName("municipalityLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.municipalityLineEdit)
        self.wardNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.wardNoLabel.setObjectName("wardNoLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wardNoLabel)
        self.wardNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.wardNoLineEdit.setObjectName("wardNoLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wardNoLineEdit)
        self.roadStreetLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.roadStreetLabel.setObjectName("roadStreetLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.roadStreetLabel)
        self.roadStreetLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.roadStreetLineEdit.setObjectName("roadStreetLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.roadStreetLineEdit)
        self.houseNoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.houseNoLabel.setObjectName("houseNoLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.houseNoLabel)
        self.houseNoLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.houseNoLineEdit.setObjectName("houseNoLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.houseNoLineEdit)
        self.villageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.villageLabel.setObjectName("villageLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.villageLabel)
        self.villageyLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.villageyLineEdit.setObjectName("villageyLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.villageyLineEdit)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registrationNoLabel.setText(_translate("MainWindow", "Registration No"))
        self.districtLabel_2.setText(_translate("MainWindow", "District"))
        self.municipalityLabel_2.setText(_translate("MainWindow", "Municipality"))
        self.wardNoLabel_2.setText(_translate("MainWindow", "Ward No"))
        self.roadStreetLabel_2.setText(_translate("MainWindow", "Road/Street"))
        self.houseNoLabel_2.setText(_translate("MainWindow", "House No"))
        self.villageCommunityLabel.setText(_translate("MainWindow", "Village/Community"))
        self.nameOfHomeownerWhoRelocatedLabel.setText(_translate("MainWindow", "Name of homeowner who relocated"))
        self.dateOfRelocatedLabel.setText(_translate("MainWindow", "Date of relocated"))
        self.reasonOfRelocatedLabel.setText(_translate("MainWindow", "Reason of relocated"))
        self.districtLabel.setText(_translate("MainWindow", "District"))
        self.municipalityLabel.setText(_translate("MainWindow", "Municipality"))
        self.wardNoLabel.setText(_translate("MainWindow", "Ward No"))
        self.roadStreetLabel.setText(_translate("MainWindow", "Road/Street"))
        self.houseNoLabel.setText(_translate("MainWindow", "House No"))
        self.villageLabel.setText(_translate("MainWindow", "Village/Community"))
        self.label.setText(_translate("MainWindow", "Where To Move"))
        self.label_2.setText(_translate("MainWindow", "The Adress From Where You Moved"))
        self.label_3.setText(_translate("MainWindow", "Details Of The Person Relocated"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
